// IMPORT SCSS
import '../scss/style.scss'
import '../scss/normalize.scss'
import '../scss/main-section.scss'
import '../scss/header.scss'
import '../scss/expand.scss'
import '../scss/brands.scss'
import '../scss/round-btn.scss'
import '../scss/aside.scss'
import '../scss/tech-repair.scss'
import '../scss/modal-call.scss'
import '../scss/modal-message.scss'
import '../scss/prices.scss'
import '../scss/footer.scss'
// IMPORT JS
import './showMoreBtn.js'
import './brands-swiper.js'
import '../js/burger-menu.js'
import '../js/readMoreBtn.js'
import '../js/tech-swiper'
import '../js/anchors.js'
import '../js/modal-call.js'
import '../js/modal-message.js'
import '../js/prices-swiper.js'
